调整GET_STAT ，“解放”MAIN，

diff --git a/trunk/lrcdis b/trunk/lrcdis
--- a/trunk/lrcdis
+++ b/trunk/lrcdis
@@ -137,8 +137,6 @@ CHECK_PLAYER() {	#自动检查播放器类型的函数
 			if pgrep -f "$i" >/dev/null ;then
 				echo -n "$i"|sed "s/quodli/quodlibet/;s/amarokapp/amarok/"
 				break
-			else
-				echo -n ""
 			fi
 		done
 	fi
@@ -155,7 +153,7 @@ SOGOU_URI(){
 	local htm a
 	htm="`wget "http://mp3.sogou.com/gecisearch.so?query="$1"" -q -T 10 -O- 2>/dev/null | iconv -f gbk`"
 	#[ "$debug" = 1 ] && echo "HTM $htm" > /tmp/htm
-	a="`echo "$htm" | grep -im1 "downlrc"|awk -F\\\" '{print $2}'`"
+	a="`echo "$htm" | grep -Fim1 "downlrc"|awk -F\\\" '{print $2}'`"
 	[ "$debug" = 1 ] && echo "A $a" >&2
 	[ "$a" = "" ]|| echo -n 'http://mp3.sogou.com/'"$a"
 }
@@ -362,7 +360,7 @@ DIS_WORDS() {		#以各种预设的模式显示文字
 				line="$line$NL"
 			fi
 		fi	
-		gnome-osd-client -f "<message id='lrcdis' osd_fake_translucent_bg='off' osd_vposition='$Vposition' osd_halignment='$Halignment' animations='$Animations' hide_timeout='$Timeout'><span size='$Size' foreground='$Foreground'>`echo -e "$line"`</span></message>"
+		gnome-osd-client -f "<message id='lrcdis' osd_fake_translucent_bg='off' osd_vposition='$Vposition' osd_halignment='$Halignment' animations='$Animations' hide_timeout='$Timeout'><span size='$Size' foreground='$Foreground'>$line</span></message>"
 	elif [ "$Dismode" = "fifo" -a -p "/dev/shm/lrcfifo" ];then
 		[ "$1" = T ] && line="****** $line ******"
 		[ "$1" = E ] && line="错误: $line"
@@ -428,7 +426,7 @@ DISPLAY() {		 #显示歌词函数
 		#例如：[02:19.46][00:59.86]XXXXXX[03:26.38][02:27.68][01:08.23]YYYYYY
 		#亦即即使你把歌曲文件连成只有一行也能正确显示而不会掉词。
 		[ "$Tm" != "$1" ] && Tm="$1" && { #只显示与上次时间不一样的
-		tmp="`echo -e "$2"|grep "$1."`" && [ "$tmp" ] && { #找到该行
+		tmp="`echo "$2"|grep -F "$1."`" && [ "$tmp" ] && { #找到该行
 		DIS_WORDS W "`echo "$tmp"|awk -F"$1" \
 		'{gsub(/(\[[0-9]*:[0-9]*\.[0-9]*\])|(\.[0-9]*\])/,"\n",$2);print $2}' \
 		| grep -v '^$' | head -n 1`"
@@ -440,6 +438,10 @@ GET_STAT() {	#获取播放器的当前状态
 
 	#没有参数，有两个独立的时间循环，一个用于产生时间信号（独立于播放器的时间信号，一定循环次数以后与播放器的时间相校准，
 	#这样减少了获取播放器时间的次数，减少 cpu 开支，但是在有拖动时可能反应有一点延迟）；另一个用于间隔一定时间后获取标题
+	#Every line is made up of two parts: 
+	#  Title This Song is Great
+	#  Time 01:23
+	#  Error 播放器已停止或未开启
 
 	local pltm0 pltm1 n0 n1 tmptm title pass ans
 
@@ -449,11 +451,11 @@ GET_STAT() {	#获取播放器的当前状态
 		((n0=${n0:-0}+1)); [ "$n0" -gt 5 ] && n0=1
 		((n1=${n1:-0}+1)); [ "$n1" -gt 6 ] && n1=1
 		sleep $Sleeptm
-		[ "$n0" = "1" ] && [ ! "`pgrep -f $Player`" ] && echo -e "lrcdisERROR未发现被支持的播放器进程！" && exit
+		[ "$n0" = "1" ] && [ ! "`pgrep -f $Player`" ] && echo "Error 未发现被支持的播放器进程！" && exit
 		[ "$n0" = "1" ] && { 
 			pltm0="`GET_PLTM $Player`"
 			if [ "${pltm0:-0}" = "$pltm1" ]|| [ "$pltm0" = "" ];then
-				echo -e "lrcdisERROR播放器已停止或未开启！"
+				echo "Error 播放器已停止或未开启！"
 				pass="continue"
 				sleep 3
 				continue
@@ -463,59 +465,15 @@ GET_STAT() {	#获取播放器的当前状态
 			fi 
 		}
 		eval "$pass"
-		[ "$n1" = "1" ] && GET_TITLE $Player $Readname
+		[ "$n1" = "1" ] && echo -n "Title " && GET_TITLE $Player $Readname
 		tmptm="$(echo "${pltm0:-0}+$Sleeptm*$n0"|bc -l)"
 		tmptm=${tmptm//.*/}
 		tmptm=${tmptm:-0}
-		ans="`printf '\n%.2d:%.2d\n' $(($tmptm/60)) $(($tmptm%60))`"
+		ans="`printf '%.2d:%.2d' $(($tmptm/60)) $(($tmptm%60))`"
 		
-		echo "$ans"
+		echo "Time $ans"
 	done
 }
-
-MAIN() {
-	#主函数（集中上面的函数实现本程序的主要目的）
-	#没有参数，用cli或osd模式正确显示应当显示的歌词
-
-	local lrc pltm line0 line1 title
-
-	Title="`GET_TITLE $Player $Readname`"
-	pltm="`GET_PLTM $Player`"
-
-	GET_STAT |while read line0;do
-		[ "$debug" = 1 ] && echo "GET_STAT: $line0<<" >&2
-		if [ "${line0//[0-9:]/}" ];then
-			Title="$line0"
-		else
-			pltm="$line0"
-		fi
-		[ "$line0" = "$line1" ] && continue
-		line1="$line0"
-
-		[ "$title" != "$Title" ] && {
-			title="$Title"
-			sleep 1
-			if [ "${Title//lrcdisERROR/}" != "$Title" ] ;then
-				DIS_WORDS E "${Title//lrcdisERROR/}"
-				continue
-			fi
-			DIS_WORDS T "$Title";
-			if [ -f "$Lrcdir/$Title.lrc" ] ;then
-				lrc="$(< "$Lrcdir/$Title.lrc")"
-			else
-				DOWNLRC "$Title"
-				if [ -f "$Lrcdir/$Title.lrc" ] ;then
-					lrc="$(< "$Lrcdir/$Title.lrc")"
-				else
-					lrc=""
-					DIS_WORDS E "未能下载歌词"
-				fi
-			fi
-		}
-		[ "$lrc" ] && DISPLAY "$pltm" "$lrc"
-	done
-}
-
 
 #===========================主流程==============================
 
@@ -569,4 +527,38 @@ else
 	[ "$Dismode" = cli ] && echo
 	exit
 fi
-MAIN
+
+MAIN() { :;} # bookmark only
+
+	#主函数（集中上面的函数实现本程序的主要目的）
+	#没有参数，用cli或osd模式正确显示应当显示的歌词
+
+	#local lrc pltm line0 line1 title
+
+	Title="`GET_TITLE $Player $Readname`"
+	pltm="`GET_PLTM $Player`"
+
+	GET_STAT |while read line0;do
+		[ "$debug" = 1 ] && echo "GET_STAT: $line0<<" >&2
+		[ "$line0" = "$line1" ] && continue
+		line1="$line0"
+		read op arg <<< "$line0"
+		[ "$op" = "Error" ] && DIS_WORDS E "$arg"
+		[ "$op" = "Title" ] && [ "$title" != "$arg" ] && [ "$arg" != "" ] && {
+			title="$arg"
+			Title="$arg"
+			DIS_WORDS T "$Title";
+			if [ -f "$Lrcdir/$Title.lrc" ] ;then
+				lrc="$(< "$Lrcdir/$Title.lrc")"
+			else
+				DOWNLRC "$Title"
+				if [ -f "$Lrcdir/$Title.lrc" ] ;then
+					lrc="$(< "$Lrcdir/$Title.lrc")"
+				else
+					lrc=""
+					DIS_WORDS E "未能下载歌词"
+				fi
+			fi
+		}
+		[ "$op" = "Time" ] && [ "$lrc" ] && DISPLAY "$arg" "$lrc"
+	done
